### ISSUE TITLE
[bug] Invalid card combination is allowed in the game

### ISSUE THREAD

**Issue by ardieorden** [marksteve/cards#1]
![Screenshot_2021-03-17_13-51-05](https://user-images.githubusercontent.com/17169362/111421468-00fdb280-8728-11eb-97d6-1f7e0b693bfd.png)

**Comment by ajatamayo** [comment]
Hi @ardieorden, can you be more clear with your issue? That card combination is not allowed in traditional pusoy dos rules.

By any chance, do you mean that the app currently allows this combination?

Thanks for the report!

**Comment by ardieorden** [comment]
> Hi @ardieorden, can you be more clear with your issue? That card combination is not allowed in traditional pusoy dos rules.
> 
> By any chance, do you mean that the app currently allows this combination?
> 
> Thanks for the report!

Hi @ajatamayo , I'll update my comment now.

**Comment by ljvmiranda921** [comment]
When can we expect a fix @marksteve ....

**Comment by marksteve** [comment]
Thank you for the report. Expect an update within this year.

**Comment by dtanman** [comment]
Hello, this happened a few times for us as well unfortunately!
![Screen Shot 2021-03-17 at 6 18 58 PM](https://user-images.githubusercontent.com/6375921/111455263-89904900-8750-11eb-998e-56a944067d98.png)

This other one is similar to the previously reported bug.
![Screen Shot 2021-03-17 at 6 30 27 PM](https://user-images.githubusercontent.com/6375921/111455333-a167cd00-8750-11eb-930d-df22cb3458b5.png)

**Comment by ghost** [comment]
@marksteve would you like some help from someone who is on leave

**Comment by marksteve** [comment]
@syk0saje gopher it!

**Comment by ghost** [comment]
fix is ready, just need write access. the problem was a `||` that should have been `&&` for full house detection. that means if your first 2 cards were a pair or if the last 3 cards were a trio, it would register as a full house. this covers all 3 samples above. regression tests were also added for each instance.
